export const COPY = {
  brand: {
    loadingAccessibilityLabel: 'A carregar Ticklane',
  },
  tabs: {
    home: 'Início',
    search: 'Buscar',
    create: 'Criar',
    favorites: 'Favoritos',
    profile: 'Perfil',
  },
  screens: {
    home: {
      title: 'Início',
      subtitle: 'Descubra processos técnicos prontos para executar.',
      popularTitle: 'Populares',
      recentTitle: 'Recentes',
      trendingTitle: 'Em alta',
    },
    search: {
      title: 'Buscar',
      subtitle: 'Encontre rapidamente um processo.',
      placeholder: 'Buscar por checklist, tag ou categoria',
      allCategoriesLabel: 'Todas',
      /** Lista já tinha itens e o filtro/pesquisa voltou a carregar na API */
      listUpdating: 'A atualizar…',
    },
    favorites: {
      title: 'Favoritos',
      subtitle: 'Seus processos salvos para acesso rápido.',
      emptyDescription: 'Favorite checklists para encontrar processos importantes rapidamente.',
      guestEmptyDescription:
        'Conecte sua conta para salvar checklists e ter elas sempre por perto.',
    },
    profile: {
      title: 'Perfil',
      guestSubtitle: 'Você está navegando como convidado.',
      authenticatedSubtitle: 'Suas checklists, favoritos e comentários.',
      editCta: 'Editar perfil',
      sections: {
        myChecklists: {
          title: 'Minhas checklists',
          emptyTitle: 'Nenhuma checklist criada',
          emptyDescription: 'Crie processos reutilizáveis e compartilhe com seu time.',
          guestEmptyDescription: 'Conecte sua conta para criar e publicar suas checklists.',
          cta: 'Criar checklist',
        },
        myFavorites: {
          title: 'Meus favoritos',
          emptyTitle: 'Nenhuma checklist favoritada',
          emptyDescription: 'Favorite processos para encontrá-los rapidamente.',
          guestEmptyDescription: 'Conecte sua conta para salvar favoritos.',
          cta: 'Explorar checklists',
        },
        myComments: {
          title: 'Meus comentários',
          emptyTitle: 'Nenhum comentário ainda',
          emptyDescription: 'Comente em checklists para trocar conhecimento com outras pessoas.',
          guestEmptyDescription: 'Conecte sua conta para comentar em checklists.',
          cta: 'Explorar checklists',
        },
        runningExecutions: {
          title: 'Execuções em curso',
          emptyTitle: 'Nenhuma execução guardada',
          emptyDescription:
            'Inicia uma execução a partir de uma checklist. Fica guardada neste aparelho e podes continuar offline.',
          guestEmptyDescription:
            'Inicia uma execução a partir de uma checklist para a teres neste aparelho, mesmo offline.',
          cta: 'Explorar checklists',
          progressOf: (done: number, total: number) => `${done} de ${total}`,
        },
      },
      connectCta: 'Entrar / Cadastrar',
      logoutCta: 'Sair',
      deleteAccount: {
        sectionTitle: 'Eliminar conta',
        warning:
          'A eliminação da conta é permanente e irreversível. Não é possível recuperar os dados depois.',
        cta: 'Eliminar conta',
        confirmTitle: 'Eliminar conta permanentemente?',
        confirmDescription:
          'Esta ação não pode ser desfeita. Serão removidos do servidor:',
        removedItems: [
          'A tua conta e sessão',
          'Todas as checklists que criaste',
          'Os teus comentários em listas de outros autores',
          'Os teus favoritos e avaliações',
        ],
        confirmCta: 'Eliminar conta permanentemente',
        cancelCta: 'Cancelar',
        deletingLabel: 'A eliminar…',
        errorTitle: 'Não foi possível eliminar a conta',
      },
    },
    checklistDetails: {
      title: 'Checklist',
      editCta: 'Editar checklist',
      cta: 'Iniciar execução',
      itemsTitle: 'Itens',
      linksTitle: 'Links úteis',
      commentsTitle: 'Comentários',
      metadataLabel: 'execuções',
      noCommentsTitle: 'Seja o primeiro a comentar',
      noCommentsDescription: 'Compartilhe dúvidas, melhorias ou avisos com quem usar essa checklist.',
      commentPlaceholder: 'Escreva um comentário...',
      commentSubmit: 'Comentar',
      commentModalTitle: 'Novo comentário',
      commentModalSubmit: 'Enviar',
      rateSheet: {
        title: 'Sua avaliação',
        descriptionPrefix: 'Deixe sua nota para',
        unrated: 'Toque nas estrelas para avaliar.',
        currentScore: 'Sua nota:',
        save: 'Salvar avaliação',
        unrate: 'Remover avaliação',
      },
    },
    execution: {
      title: 'Execução',
      progressLabel: 'Progresso',
      progressCount: (done: number, total: number) => `${done} de ${total}`,
      offlineNotice:
        'Cópia guardada neste dispositivo. Não altera a checklist original nem sincroniza com o servidor.',
      itemsTitle: 'Itens',
      linksTitle: 'Links úteis',
      notFoundTitle: 'Execução não encontrada',
      notFoundDescription: 'Esta sessão não existe neste dispositivo ou já foi removida.',
      webUnavailable:
        'O armazenamento local não está disponível na versão web. Usa a app no telemóvel ou tablet.',
    },
    runningExecutionsList: {
      title: 'Execuções em curso',
      subtitle: 'Cópias guardadas neste dispositivo para concluíres offline.',
      emptyTitle: 'Nenhuma execução em curso',
      emptyDescription: 'Inicia uma execução a partir de uma checklist para a veres aqui.',
      exploreCta: 'Explorar checklists',
    },
    profileMyChecklistsList: {
      title: 'Minhas checklists',
      subtitle: 'Checklists que publicaste na comunidade.',
      emptyTitle: 'Nenhuma checklist criada',
      emptyDescription: 'Cria um processo reutilizável e partilha com o teu time.',
      exploreCta: 'Explorar checklists',
      createCta: 'Criar checklist',
      guestEmptyDescription: 'Conecta a conta para criar e publicar checklists.',
    },
    profileMyFavoritesList: {
      title: 'Meus favoritos',
      subtitle: 'Checklists que guardaste para acesso rápido.',
      emptyTitle: 'Nenhuma checklist favoritada',
      emptyDescription: 'Explora a comunidade e guarda os processos que mais usas.',
      exploreCta: 'Explorar checklists',
      guestEmptyDescription:
        'Conecte sua conta para salvar checklists e ter elas sempre por perto.',
    },
    itemDetails: {
      itemLabel: 'Item',
      commentsTitle: 'Comentários do item',
      noCommentsTitle: 'Sem comentários neste item',
      noCommentsDescription: 'Aproveite e seja o primeiro a deixar uma observação.',
      notFoundTitle: 'Item não encontrado',
      notFoundDescription: 'Este item pode ter sido removido ou movido.',
    },
    editChecklist: {
      title: 'Editar checklist',
      subtitle: 'Atualize o processo e os passos da tua lista.',
      cta: 'Guardar alterações',
      sections: {
        details: 'Detalhes',
        category: 'Categoria',
        tags: 'Tags',
        items: 'Itens',
      },
      fields: {
        titleLabel: 'Título',
        titlePlaceholder: 'Ex: Deploy iOS na App Store',
        descriptionLabel: 'Descrição',
        descriptionPlaceholder: 'Resumo curto do processo (opcional)',
        tagsLabel: 'Tags',
        tagsPlaceholder: 'Adicione uma tag e pressione Enter',
        itemTitlePlaceholder: 'Título do item',
        itemDescriptionPlaceholder: 'Descrição (opcional)',
      },
      validation: {
        titleRequired: 'Informe um título.',
        categoryRequired: 'Selecione uma categoria.',
        itemsRequired: 'Adicione pelo menos um item.',
        itemTitleRequired: 'Cada item precisa de um título.',
        notFound: 'Checklist não encontrada.',
      },
    },
    create: {
      title: 'Nova checklist',
      subtitle: 'Compartilhe um processo reutilizável com a comunidade.',
      cta: 'Publicar',
      sections: {
        details: 'Detalhes',
        category: 'Categoria',
        tags: 'Tags',
        items: 'Itens',
      },
      fields: {
        titleLabel: 'Título',
        titlePlaceholder: 'Ex: Deploy iOS na App Store',
        descriptionLabel: 'Descrição',
        descriptionPlaceholder: 'Resumo curto do processo (opcional)',
        tagsLabel: 'Tags',
        tagsPlaceholder: 'Adicione uma tag e pressione Enter',
        itemTitlePlaceholder: 'Título do item',
        itemDescriptionPlaceholder: 'Descrição (opcional)',
      },
      addItem: 'Adicionar item',
      removeItem: 'Remover',
      removeTag: 'Remover tag',
      categoryEmpty: 'Selecione uma categoria',
      validation: {
        titleRequired: 'Informe um título.',
        categoryRequired: 'Selecione uma categoria.',
        itemsRequired: 'Adicione pelo menos um item.',
        itemTitleRequired: 'Cada item precisa de um título.',
        notFound: 'Checklist não encontrada.',
      },
    },
    auth: {
      title: 'Entrar ou cadastrar-se',
      subtitle:
        'Insere o teu e-mail e enviamos um código de acesso. No primeiro acesso criamos a tua conta.',
      codeTitle: 'Confirmar código',
      codeSubtitle: 'Verifica o teu e-mail e introduz o código de 6 dígitos.',
    },
    profileEdit: {
      title: 'Editar perfil',
      subtitle: 'Atualize o seu nome, foto e bio.',
      nameLabel: 'Nome',
      nameHelper: 'Como queres ser identificado em listas e comentários.',
      bioLabel: 'Bio',
      bioPlaceholder: 'Conta em poucas palavras o que fazes ou em que te interessa.',
      bioHelper: (used: number, max: number) => `${used}/${max} caracteres`,
      avatarTitle: 'Foto de perfil',
      avatarHelper: 'Formatos: JPEG, PNG ou WebP. Máx 2 MB.',
      avatarChangeCta: 'Trocar foto',
      avatarUploadCta: 'Carregar foto',
      avatarRemoveCta: 'Remover foto',
      avatarUploadingLabel: 'A carregar…',
      avatarRemovingLabel: 'A remover…',
      saveCta: 'Guardar alterações',
      savingLabel: 'A guardar…',
      cancelCta: 'Cancelar',
      successMessage: 'Perfil actualizado.',
      avatarUpdatedMessage: 'Avatar actualizado.',
      avatarRemovedMessage: 'Avatar removido. Estamos a usar as iniciais.',
      tooLargeMessage: 'Imagem demasiado grande (máx 2 MB).',
      invalidTypeMessage: 'Usa um ficheiro JPEG, PNG ou WebP.',
      permissionDenied: 'Sem permissão para aceder às fotos.',
    },
    author: {
      checklistsTitle: 'Checklists publicadas',
      emptyTitle: 'Nenhuma checklist publicada',
      emptyDescription: 'Esse autor ainda não publicou checklists.',
      notFoundTitle: 'Autor não encontrado',
      notFoundDescription: 'Não conseguimos carregar este perfil.',
      stats: {
        checklists: 'Checklists',
        comments: 'Comentários',
        favorites: 'Salvamentos',
      },
    },
  },
  auth: {
    gate: {
      title: 'Entrar para continuar',
      descriptionPrefix: 'Vais precisar de uma conta para',
      cancel: 'Agora não',
      intents: {
        favorite: 'salvar checklists nos seus favoritos',
        comment: 'comentar em checklists',
        rate: 'avaliar checklists',
        create: 'criar e compartilhar suas próprias checklists',
        execute: 'salvar o histórico das suas execuções',
        fallback: 'continuar essa ação',
      },
    },
    guestBadge: 'Convidado',
    keepBrowsing: 'Continuar navegando',
  },
  states: {
    placeholderTitle: 'Em construção',
    placeholderDescription: 'Esta tela faz parte do shell de navegação e será implementada em fases futuras.',
    emptyTitle: 'Nada por aqui ainda',
  },
  actions: {
    back: 'Voltar',
    seeAll: 'Ver todas',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    save: 'Salvar',
    submit: 'Enviar',
    publish: 'Publicar',
    retry: 'Tentar novamente',
    toggleTheme: 'Alternar tema',
    viewAll: 'Ver tudo',
    openChecklist: 'Abrir checklist',
    favorite: 'Adicionar aos favoritos',
    unfavorite: 'Remover dos favoritos',
    rateChecklist: 'Avaliar checklist',
  },
  settings: {
    appearanceLabel: 'Aparência',
    appearanceDescription: 'Escolha entre tema claro ou escuro.',
    themeDark: 'Escuro',
    themeLight: 'Claro',
  },
} as const;
