name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  CD:
    if: github.event.workflow_run.conclusion == 'success'
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Deploy
        run: echo "Deploying..."