name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
  CD:
    needs: CI
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v9
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Get Goole Play Credentials
        env:
          GOOGLE_PLAY_CONSOLE_API: ${{ secrets.GOOGLE_PLAY_CONSOLE_API }}
        run: |
          echo $GOOGLE_PLAY_CONSOLE_API > google-play-console-api.b64
          base64 -d google-play-console-api.b64 > google-play-console-api.json
      
      # Build and Submit Android and IOS
      - name: Build and Submit Android and IOS
        run: |
          EXPO_APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.EAS_APPLE_PASSWORD }} \
          eas build \
          --platform all \
          --profile production \
          --non-interactive \
          --auto-submit \
          --no-wait


      
  